#!/bin/bash
declare -f showHelp
showHelp()
{
cat <<EOF
usage: $0 [-u username] [-p password] [-i ip] [-h]
EOF
exit 1
}
 
# 解析参数
while getopts ":u:p:i:h" arg
do
  case $arg in
		u)
			user="【】"
			;;
		p)
			password="【】"
			;;
		h)
			showHelp
			;;
		i)
			ip=$OPTARG
			;;
		:|?|*)
			showHelp
			;;
	esac
done
 
# 如果没有获取参数,则交互式输入
if [ -z "$user" ]
then
	read -p"username:" user
fi
 
if [ -z "$password" ]
then
	stty -echo
	read -p"password:" password
	stty echo
	echo
fi
 
# 检查参数是否成功输入
[ -z "$user" ] && showHelp
[ -z "$password" ] && showHelp
 
# 发送post数据, 注意这里没有保存cookies
ip=${ip:-"10.3.8.211"} # 这里设置ip的缺省值
curl -A "Mozilla/4.0(compatible;MSIE 6.0;Windows NT 5.0)" -d "DDDDD=$user&upass=$password&save_me=1&R1=0" "$ip"  -o output.html 2>/dev/null

echo "Success Login!"
