#!/bin/sh

((randnum=$RANDOM*$RANDOM))
#echo $randnum
for((i=1;;i++))
do
a=`curl http://3.hurray.sinaapp.com/try/shellpost.php`
if ((a==randnum));then
echo "成功！"
break
else
if((i!=1));then
sleep $i
echo "失败！"
fi
echo "第"$i"次连接"
curl -d "msg=${myinput}&key=${randnum}" http://3.hurray.sinaapp.com/try/shellpost.php
fi
done